USE cedcd;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  
    ALTER TABLE cohort
    ADD `type` VARCHAR(20) NOT NULL DEFAULT 'Etiology',
    ADD `outdated` BOOLEAN NOT NULL DEFAULT false;

    UPDATE cohort
    SET `type` = 'Survivor'
    WHERE acronym = 'Pathways';
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;


