USE cedcd;
SET sql_safe_updates=0;

DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

    UPDATE cohort
    SET `outdated` = true
    WHERE publish_time < DATE_SUB(NOW(),INTERVAL 2 YEAR);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;

SET sql_safe_updates=1;