CREATE TABLE cohort_basic (
  cohort_id int(11) not null AUTO_INCREMENT,
  cohort_name varchar(500) NULL,
  cohort_acronym varchar(100) NULL,
  cohort_web_site varchar(200) NULL,
  completed_by_name varchar(100) NULL,
  completed_by_position varchar(100) NULL,
  completed_by_phone varchar(100) NULL,
  completed_by_email varchar(100) NULL,
  contact_name varchar(100) NULL,
  contact_position varchar(100) NULL,
  contact_phone varchar(100) NULL,
  contact_email varchar(100) NULL,
  clarification_contact int(1) NULL,
  pi_name_1 varchar(100) NULL,
  pi_institution_1 varchar(100) NULL,
  pi_email_1 varchar(100) NULL,
  pi_name_2 varchar(100) NULL,
  pi_institution_2 varchar(100) NULL,
  pi_email_2 varchar(100) NULL,
  pi_name_3 varchar(100) NULL,
  pi_institution_3 varchar(100) NULL,
  pi_email_3 varchar(100) NULL,
  pi_name_4 varchar(100) NULL,
  pi_institution_4 varchar(100) NULL,
  pi_email_4 varchar(100) NULL,
  pi_name_5 varchar(100) NULL,
  pi_institution_5 varchar(100) NULL,
  pi_email_5 varchar(100) NULL,
  pi_name_6 varchar(100) NULL,
  pi_institution_6 varchar(100) NULL,
  pi_email_6 varchar(100) NULL,
  collab_contact_name varchar(100) NULL,
  collab_contact_position varchar(100) NULL,
  collab_contact_phone varchar(100) NULL,
  collab_contact_email varchar(100) NULL,
  same_as_a3a int(1) NULL,
  same_as_a3b int(1) NULL,
  request_procedures_web int(1) NULL,
  request_procedures_web_url varchar(100) NULL,
  request_procedures_pdf int(1) NULL,
  request_procedures_none int(1) NULL,
  cohort_description varchar(5000) NULL,
  eligible_gender int(1) NULL,
  eligible_disease int(1) NULL,
  eligible_disease_cancer_specify varchar(100) NULL,
  eligible_disease_other_specify varchar(100) NULL,
  enrollment_total int(10) NULL,
  enrollment_year_start int(4) NULL,
  enrollment_year_end int(4) NULL,
  enrollment_ongoing int(1) NULL,
  enrollment_target int(10) NULL,
  enrollment_year_complete int(4) NULL,
  enrollment_age_min int(3) NULL,
  enrollment_age_max int(3) NULL,
  enrollment_age_median int(3) NULL,
  enrollment_age_mean int(3) NULL,
  time_interval varchar(200) NULL,
  most_recent_year int(4) NULL,
  data_collected_in_person int(1) NULL,
  data_collected_phone int(1) NULL,
  data_collected_paper int(1) NULL,
  data_collected_web int(1) NULL,
  data_collected_other int(1) NULL,
  data_collected_other_specify varchar(200) NULL,
  other_tools int(1) NULL,
  other_tools_specify varchar(200) NULL,
  restrictions_none int(1) NULL,
  restrictions_require_collaboration int(1) NULL,
  restrictions_require_irb int(1) NULL,
  restrictions_require_agreement int(1) NULL,
  restrictions_on_genetic_use int(1) NULL,
  restrictions_on_linking int(1) NULL,
  restrictions_on_commercial_use int(1) NULL,
  restrictions_other int(1) NULL,
  restrictions_other_specify varchar(200) NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (cohort_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into cohort_basic (
  cohort_id,
  cohort_name,
  cohort_acronym,
  cohort_web_site,
  completed_by_name,
  completed_by_position,
  completed_by_phone,
  completed_by_email,
  contact_name,
  contact_position,
  contact_phone,
  contact_email,
  clarification_contact,
  pi_name_1,
  pi_institution_1,
  pi_email_1,
  pi_name_2,
  pi_institution_2,
  pi_email_2,
  pi_name_3,
  pi_institution_3,
  pi_email_3,
  pi_name_4,
  pi_institution_4,
  pi_email_4,
  pi_name_5,
  pi_institution_5,
  pi_email_5,
  pi_name_6,
  pi_institution_6,
  pi_email_6,
  collab_contact_name,
  collab_contact_position,
  collab_contact_phone,
  collab_contact_email,
  same_as_a3a,
  same_as_a3b,
  request_procedures_web,
  request_procedures_web_url,
  request_procedures_pdf,
  request_procedures_none,
  cohort_description,
  eligible_gender,
  eligible_disease,
  eligible_disease_cancer_specify,
  eligible_disease_other_specify,
  enrollment_total,
  enrollment_year_start,
  enrollment_year_end,
  enrollment_ongoing,
  enrollment_target,
  enrollment_year_complete,
  enrollment_age_min,
  enrollment_age_max,
  enrollment_age_median,
  enrollment_age_mean,
  time_interval,
  most_recent_year,
  data_collected_in_person,
  data_collected_phone,
  data_collected_paper,
  data_collected_web,
  data_collected_other,
  data_collected_other_specify,
  other_tools,
  other_tools_specify,
  restrictions_none,
  restrictions_require_collaboration,
  restrictions_require_irb,
  restrictions_require_agreement,
  restrictions_on_genetic_use,
  restrictions_on_linking,
  restrictions_on_commercial_use,
  restrictions_other,
  restrictions_other_specify
)
select cohort_id,
  cohort_name,
  cohort_acronym,
  cohort_web_site,
  completed_by_name,
  completed_by_position,
  completed_by_phone,
  completed_by_email,
  contact_name,
  contact_position,
  contact_phone,
  contact_email,
  clarification_contact,
  pi_name_1,
  pi_institution_1,
  pi_email_1,
  pi_name_2,
  pi_institution_2,
  pi_email_2,
  pi_name_3,
  pi_institution_3,
  pi_email_3,
  pi_name_4,
  pi_institution_4,
  pi_email_4,
  pi_name_5,
  pi_institution_5,
  pi_email_5,
  pi_name_6,
  pi_institution_6,
  pi_email_6,
  collab_contact_name,
  collab_contact_position,
  collab_contact_phone,
  collab_contact_email,
  same_as_a3a,
  same_as_a3b,
  request_procedures_web,
  request_procedures_web_url,
  request_procedures_pdf,
  request_procedures_none,
  cohort_description,
  (case when eligible_gender = "Both" then 0
        when eligible_gender = "Female" then 1
        when eligible_gender = "Male" then 2
        else -1
   end
  ),
  (case when eligible_disease = "A_Eligible_Disease_Cancer" then 0
        when eligible_disease = "A_Eligible_Disease_NCancer" then 1
        when eligible_disease = "A_Eligible_Disease_Other" then 2
        else -1
   end
  ),
  eligible_disease_cancer_specify,
  eligible_disease_other_specify,
  enrollment_total,
  enrollment_year_start,
  enrollment_year_end,
  (case when enrollment_ongoing = "No" then 0
        when enrollment_ongoing = "Yes" then 1
        else -1
   end
  ),
  enrollment_target,
  enrollment_year_complete,
  enrollment_age_min,
  enrollment_age_max,
  enrollment_age_median,
  enrollment_age_mean,
  time_interval,
  most_recent_year,
  (case when data_collected_in_person = "No" then 0
        when data_collected_in_person = "Yes" then 1
        else -1
   end
  ),
  (case when data_collected_phone = "No" then 0
        when data_collected_phone = "Yes" then 1
        else -1
   end
  ),
  (case when data_collected_paper = "No" then 0
        when data_collected_paper = "Yes" then 1
        else -1
   end
  ),
  (case when data_collected_web = "No" then 0
        when data_collected_web = "Yes" then 1
        else -1
   end
  ),
  (case when data_collected_other = "No" then 0
        when data_collected_other = "Yes" then 1
        else -1
   end
  ),
  data_collected_other_specify,
  (case when other_tools = "No" then 0
        when other_tools = "Yes" then 1
        else -1
   end
  ),
  other_tools_specify,
  restrictions_none,
  restrictions_require_collaboration,
  restrictions_require_irb,
  restrictions_require_agreement,
  restrictions_on_genetic_use,
  restrictions_on_linking,
  restrictions_on_commercial_use,
  restrictions_other,
  restrictions_other_specify
from cohort_data

Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column To disable safe mode, 
toggle the option in Preferences -> SQL Editor and reconnect.
