insert into cohort_specimens(
	cohort_id,
	bio_no_cancer_serum,
	bio_no_cancer_buffy,
	bio_no_cancer_saliva,
	bio_no_cancer_urine,
	bio_no_cancer_feces,
	bio_no_cancer_tumor_tissue_1,
	bio_no_cancer_tumor_tissue_2,
	bio_oropharyngeal_serum,
	bio_oropharyngeal_buffy,
	bio_oropharyngeal_saliva,
	bio_oropharyngeal_urine,
	bio_oropharyngeal_feces,
	bio_oropharyngeal_tumor_tissue_1,
	bio_oropharyngeal_tumor_tissue_2,
	bio_esophagus_serum,
	bio_esophagus_buffy,
	bio_esophagus_saliva,
	bio_esophagus_urine,
	bio_esophagus_feces,
	bio_esophagus_tumor_tissue_1,
	bio_esophagus_tumor_tissue_2,
	bio_stomach_serum,
	bio_stomach_buffy,
	bio_stomach_saliva,
	bio_stomach_urine,
	bio_stomach_feces,
	bio_stomach_tumor_tissue_1,
	bio_stomach_tumor_tissue_2,
	bio_small_intestine_serum,
	bio_small_intestine_buffy,
	bio_small_intestine_saliva,
	bio_small_intestine_urine,
	bio_small_intestine_feces,
	bio_small_intestine_tumor_tissue_1,
	bio_small_intestine_tumor_tissue_2,
	bio_colon_serum,
	bio_colon_buffy,
	bio_colon_saliva,
	bio_colon_urine,
	bio_colon_feces,
	bio_colon_tumor_tissue_1,
	bio_colon_tumor_tissue_2,
	bio_rectum_serum,
	bio_rectum_buffy,
	bio_rectum_saliva,
	bio_rectum_urine,
	bio_rectum_feces,
	bio_rectum_tumor_tissue_1,
	bio_rectum_tumor_tissue_2,
	bio_liver_serum,
	bio_liver_buffy,
	bio_liver_saliva,
	bio_liver_urine,
	bio_liver_feces,
	bio_liver_tumor_tissue_1,
	bio_liver_tumor_tissue_2,
	bio_gall_bladder_serum,
	bio_gall_bladder_buffy,
	bio_gall_bladder_saliva,
	bio_gall_bladder_urine,
	bio_gall_bladder_feces,
	bio_gall_bladder_tumor_tissue_1,
	bio_gall_bladder_tumor_tissue_2,
	bio_pancreas_serum,
	bio_pancreas_buffy,
	bio_pancreas_saliva,
	bio_pancreas_urine,
	bio_pancreas_feces,
	bio_pancreas_tumor_tissue_1,
	bio_pancreas_tumor_tissue_2,
	bio_lung_serum,
	bio_lung_buffy,
	bio_lung_saliva,
	bio_lung_urine,
	bio_lung_feces,
	bio_lung_tumor_tissue_1,
	bio_lung_tumor_tissue_2,
	bio_bone_serum,
	bio_bone_buffy,
	bio_bone_saliva,
	bio_bone_urine,
	bio_bone_feces,
	bio_bone_tumor_tissue_1,
	bio_bone_tumor_tissue_2,
	bio_melanoma_serum,
	bio_melanoma_buffy,
	bio_melanoma_saliva,
	bio_melanoma_urine,
	bio_melanoma_feces,
	bio_melanoma_tumor_tissue_1,
	bio_melanoma_tumor_tissue_2,
	bio_breast_serum,
	bio_breast_buffy,
	bio_breast_saliva,
	bio_breast_urine,
	bio_breast_feces,
	bio_breast_tumor_tissue_1,
	bio_breast_tumor_tissue_2,
	bio_cervix_serum,
	bio_cervix_buffy,
	bio_cervix_saliva,
	bio_cervix_urine,
	bio_cervix_feces,
	bio_cervix_tumor_tissue_1,
	bio_cervix_tumor_tissue_2,
	bio_corpus_serum,
	bio_corpus_buffy,
	bio_corpus_saliva,
	bio_corpus_urine,
	bio_corpus_feces,
	bio_corpus_tumor_tissue_1,
	bio_corpus_tumor_tissue_2,
	bio_ovary_serum,
	bio_ovary_buffy,
	bio_ovary_saliva,
	bio_ovary_urine,
	bio_ovary_feces,
	bio_ovary_tumor_tissue_1,
	bio_ovary_tumor_tissue_2,
	bio_prostate_serum,
	bio_prostate_buffy,
	bio_prostate_saliva,
	bio_prostate_urine,
	bio_prostate_feces,
	bio_prostate_tumor_tissue_1,
	bio_prostate_tumor_tissue_2,
	bio_bladder_serum,
	bio_bladder_buffy,
	bio_bladder_saliva,
	bio_bladder_urine,
	bio_bladder_feces,
	bio_bladder_tumor_tissue_1,
	bio_bladder_tumor_tissue_2,
	bio_kidney_serum,
	bio_kidney_buffy,
	bio_kidney_saliva,
	bio_kidney_urine,
	bio_kidney_feces,
	bio_kidney_tumor_tissue_1,
	bio_kidney_tumor_tissue_2,
	bio_brain_serum,
	bio_brain_buffy,
	bio_brain_saliva,
	bio_brain_urine,
	bio_brain_feces,
	bio_brain_tumor_tissue_1,
	bio_brain_tumor_tissue_2,
	bio_thyroid_serum,
	bio_thyroid_buffy,
	bio_thyroid_saliva,
	bio_thyroid_urine,
	bio_thyroid_feces,
	bio_thyroid_tumor_tissue_1,
	bio_thyroid_tumor_tissue_2,
	bio_lymphoma_serum,
	bio_lymphoma_buffy,
	bio_lymphoma_saliva,
	bio_lymphoma_urine,
	bio_lymphoma_feces,
	bio_lymphoma_tumor_tissue_1,
	bio_lymphoma_tumor_tissue_2,
	bio_myeloma_serum,
	bio_myeloma_buffy,
	bio_myeloma_saliva,
	bio_myeloma_urine,
	bio_myeloma_feces,
	bio_myeloma_tumor_tissue_1,
	bio_myeloma_tumor_tissue_2,
	bio_leukemia_serum,
	bio_leukemia_buffy,
	bio_leukemia_saliva,
	bio_leukemia_urine,
	bio_leukemia_feces,
	bio_leukemia_tumor_tissue_1,
	bio_leukemia_tumor_tissue_2,
	bio_all_other_cancers_serum,
	bio_all_other_cancers_buffy,
	bio_all_other_cancers_saliva,
	bio_all_other_cancers_urine,
	bio_all_other_cancers_feces,
	bio_all_other_cancers_tumor_tissue_1,
	bio_all_other_cancers_tumor_tissue_2,
	bio_blood_baseline,
	bio_blood_baseline_serum,
	bio_blood_baseline_plasma,
	bio_blood_baseline_buffy_coat,
	bio_blood_baseline_other_derivative,
	bio_blood_other_time,
	bio_blood_other_time_serum,
	bio_blood_other_time_plasma,
	bio_blood_other_time_buffy_coat,
	bio_blood_other_time_other_derivative,
	bio_buccal_saliva_baseline,
	bio_buccal_saliva_other_time,
	bio_tissue_baseline,
	bio_tissue_other_time,
	bio_tumor_block_info,
	bio_genotyping_data,
	bio_sequencing_data_exome,
	bio_sequencing_data_whole_genome,
	bio_epigenetic_or_metabolic_markers,
	bio_other_omics_data
)
select 
	cohort_id,
	bio_no_cancer_serum,
	bio_no_cancer_buffy,
	bio_no_cancer_saliva,
	bio_no_cancer_urine,
	bio_no_cancer_feces,
	bio_no_cancer_tumor_tissue_1,
	bio_no_cancer_tumor_tissue_2,
	bio_oropharyngeal_serum,
	bio_oropharyngeal_buffy,
	bio_oropharyngeal_saliva,
	bio_oropharyngeal_urine,
	bio_oropharyngeal_feces,
	bio_oropharyngeal_tumor_tissue_1,
	bio_oropharyngeal_tumor_tissue_2,
	bio_esophagus_serum,
	bio_esophagus_buffy,
	bio_esophagus_saliva,
	bio_esophagus_urine,
	bio_esophagus_feces,
	bio_esophagus_tumor_tissue_1,
	bio_esophagus_tumor_tissue_2,
	bio_stomach_serum,
	bio_stomach_buffy,
	bio_stomach_saliva,
	bio_stomach_urine,
	bio_stomach_feces,
	bio_stomach_tumor_tissue_1,
	bio_stomach_tumor_tissue_2,
	bio_small_intestine_serum,
	bio_small_intestine_buffy,
	bio_small_intestine_saliva,
	bio_small_intestine_urine,
	bio_small_intestine_feces,
	bio_small_intestine_tumor_tissue_1,
	bio_small_intestine_tumor_tissue_2,
	bio_colon_serum,
	bio_colon_buffy,
	bio_colon_saliva,
	bio_colon_urine,
	bio_colon_feces,
	bio_colon_tumor_tissue_1,
	bio_colon_tumor_tissue_2,
	bio_rectum_serum,
	bio_rectum_buffy,
	bio_rectum_saliva,
	bio_rectum_urine,
	bio_rectum_feces,
	bio_rectum_tumor_tissue_1,
	bio_rectum_tumor_tissue_2,
	bio_liver_serum,
	bio_liver_buffy,
	bio_liver_saliva,
	bio_liver_urine,
	bio_liver_feces,
	bio_liver_tumor_tissue_1,
	bio_liver_tumor_tissue_2,
	bio_gall_bladder_serum,
	bio_gall_bladder_buffy,
	bio_gall_bladder_saliva,
	bio_gall_bladder_urine,
	bio_gall_bladder_feces,
	bio_gall_bladder_tumor_tissue_1,
	bio_gall_bladder_tumor_tissue_2,
	bio_pancreas_serum,
	bio_pancreas_buffy,
	bio_pancreas_saliva,
	bio_pancreas_urine,
	bio_pancreas_feces,
	bio_pancreas_tumor_tissue_1,
	bio_pancreas_tumor_tissue_2,
	bio_lung_serum,
	bio_lung_buffy,
	bio_lung_saliva,
	bio_lung_urine,
	bio_lung_feces,
	bio_lung_tumor_tissue_1,
	bio_lung_tumor_tissue_2,
	bio_bone_serum,
	bio_bone_buffy,
	bio_bone_saliva,
	bio_bone_urine,
	bio_bone_feces,
	bio_bone_tumor_tissue_1,
	bio_bone_tumor_tissue_2,
	bio_melanoma_serum,
	bio_melanoma_buffy,
	bio_melanoma_saliva,
	bio_melanoma_urine,
	bio_melanoma_feces,
	bio_melanoma_tumor_tissue_1,
	bio_melanoma_tumor_tissue_2,
	bio_breast_serum,
	bio_breast_buffy,
	bio_breast_saliva,
	bio_breast_urine,
	bio_breast_feces,
	bio_breast_tumor_tissue_1,
	bio_breast_tumor_tissue_2,
	bio_cervix_serum,
	bio_cervix_buffy,
	bio_cervix_saliva,
	bio_cervix_urine,
	bio_cervix_feces,
	bio_cervix_tumor_tissue_1,
	bio_cervix_tumor_tissue_2,
	bio_corpus_serum,
	bio_corpus_buffy,
	bio_corpus_saliva,
	bio_corpus_urine,
	bio_corpus_feces,
	bio_corpus_tumor_tissue_1,
	bio_corpus_tumor_tissue_2,
	bio_ovary_serum,
	bio_ovary_buffy,
	bio_ovary_saliva,
	bio_ovary_urine,
	bio_ovary_feces,
	bio_ovary_tumor_tissue_1,
	bio_ovary_tumor_tissue_2,
	bio_prostate_serum,
	bio_prostate_buffy,
	bio_prostate_saliva,
	bio_prostate_urine,
	bio_prostate_feces,
	bio_prostate_tumor_tissue_1,
	bio_prostate_tumor_tissue_2,
	bio_bladder_serum,
	bio_bladder_buffy,
	bio_bladder_saliva,
	bio_bladder_urine,
	bio_bladder_feces,
	bio_bladder_tumor_tissue_1,
	bio_bladder_tumor_tissue_2,
	bio_kidney_serum,
	bio_kidney_buffy,
	bio_kidney_saliva,
	bio_kidney_urine,
	bio_kidney_feces,
	bio_kidney_tumor_tissue_1,
	bio_kidney_tumor_tissue_2,
	bio_brain_serum,
	bio_brain_buffy,
	bio_brain_saliva,
	bio_brain_urine,
	bio_brain_feces,
	bio_brain_tumor_tissue_1,
	bio_brain_tumor_tissue_2,
	bio_thyroid_serum,
	bio_thyroid_buffy,
	bio_thyroid_saliva,
	bio_thyroid_urine,
	bio_thyroid_feces,
	bio_thyroid_tumor_tissue_1,
	bio_thyroid_tumor_tissue_2,
	bio_lymphoma_serum,
	bio_lymphoma_buffy,
	bio_lymphoma_saliva,
	bio_lymphoma_urine,
	bio_lymphoma_feces,
	bio_lymphoma_tumor_tissue_1,
	bio_lymphoma_tumor_tissue_2,
	bio_myeloma_serum,
	bio_myeloma_buffy,
	bio_myeloma_saliva,
	bio_myeloma_urine,
	bio_myeloma_feces,
	bio_myeloma_tumor_tissue_1,
	bio_myeloma_tumor_tissue_2,
	bio_leukemia_serum,
	bio_leukemia_buffy,
	bio_leukemia_saliva,
	bio_leukemia_urine,
	bio_leukemia_feces,
	bio_leukemia_tumor_tissue_1,
	bio_leukemia_tumor_tissue_2,
	bio_all_other_cancers_serum,
	bio_all_other_cancers_buffy,
	bio_all_other_cancers_saliva,
	bio_all_other_cancers_urine,
	bio_all_other_cancers_feces,
	bio_all_other_cancers_tumor_tissue_1,
	bio_all_other_cancers_tumor_tissue_2,
	(case when bio_blood_baseline = "No" then 0
	    when bio_blood_baseline = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_baseline_serum = "No" then 0
	    when bio_blood_baseline_serum = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_baseline_plasma = "No" then 0
	    when bio_blood_baseline_plasma = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_baseline_buffy_coat = "No" then 0
	    when bio_blood_baseline_buffy_coat = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_baseline_other_derivative = "No" then 0
	    when bio_blood_baseline_other_derivative = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_other_time = "No" then 0
	    when bio_blood_other_time = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_other_time_serum = "No" then 0
	    when bio_blood_other_time_serum = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_other_time_plasma = "No" then 0
	    when bio_blood_other_time_plasma = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_other_time_buffy_coat = "No" then 0
	    when bio_blood_other_time_buffy_coat = "Yes" then 1
	    else -1
	end
	),
	(case when bio_blood_other_time_other_derivative = "No" then 0
	    when bio_blood_other_time_other_derivative = "Yes" then 1
	    else -1
	end
	),
	(case when bio_buccal_saliva_baseline = "No" then 0
	    when bio_buccal_saliva_baseline = "Yes" then 1
	    else -1
	end
	),
	(case when bio_buccal_saliva_other_time = "No" then 0
	    when bio_buccal_saliva_other_time = "Yes" then 1
	    else -1
	end
	),
	(case when bio_tissue_baseline = "No" then 0
	    when bio_tissue_baseline = "Yes" then 1
	    else -1
	end
	),
	(case when bio_tissue_other_time = "No" then 0
	    when bio_tissue_other_time = "Yes" then 1
	    else -1
	end
	),
	(case when bio_tumor_block_info = "No" then 0
	    when bio_tumor_block_info = "Yes" then 1
	    else -1
	end
	),
	(case when bio_genotyping_data = "No" then 0
	    when bio_genotyping_data = "Yes" then 1
	    else -1
	end
	),
	(case when bio_sequencing_data_exome = "No" then 0
	    when bio_sequencing_data_exome = "Yes" then 1
	    else -1
	end
	),
	(case when bio_sequencing_data_whole_genome = "No" then 0
	    when bio_sequencing_data_whole_genome = "Yes" then 1
	    else -1
	end
	),
	(case when bio_epigenetic_or_metabolic_markers = "No" then 0
	    when bio_epigenetic_or_metabolic_markers = "Yes" then 1
	    else -1
	end
	),
	(case when bio_other_omics_data = "No" then 0
	    when bio_other_omics_data = "Yes" then 1
	    else -1
	end
	)
from cohort_data