-- -----------------------------------------------------------------------------------------------------------
-- view; `cohort_summary`
-- -----------------------------------------------------------------------------------------------------------

DROP VIEW IF EXISTS `cohort_summary` ;

CREATE VIEW `cohort_summary` AS 

	SELECT 
		`cb`.`cohort_id` AS `cohort_id`,`cb`.`cohort_name` AS `cohort_name`,`cb`.
		`cohort_acronym` AS `cohort_acronym`,`cb`.`cohort_web_site` AS `cohort_web_site`,
		`cb`.`eligible_gender` AS `eligible_gender`,`cb`.`eligible_disease` AS `eligible_disease`,`cb`.`eligible_disease_other_specify` AS `eligible_disease_other_specify`,`cb`.`enrollment_age_min` AS `enrollment_age_min`,
		`cb`.`enrollment_age_max` AS `enrollment_age_max`,`cb`.`update_time` AS `update_time`,`ce`.`race_ai_nonhispanic_females` AS `race_ai_nonhispanic_females`,`ce`.`race_ai_nonhispanic_males` AS `race_ai_nonhispanic_males`,
		`ce`.`race_ai_nonhispanic_unknown` AS `race_ai_nonhispanic_unknown`,`ce`.`race_ai_hispanic_females` AS `race_ai_hispanic_females`,`ce`.`race_ai_hispanic_males` AS `race_ai_hispanic_males`,
		`ce`.`race_ai_hispanic_unknown` AS `race_ai_hispanic_unknown`,`ce`.`race_ai_unknown_females` AS `race_ai_unknown_females`,`ce`.`race_ai_unknown_males` AS `race_ai_unknown_males`,
		`ce`.`race_ai_unknown_unknown` AS `race_ai_unknown_unknown`,`ce`.`race_ai_total` AS `race_ai_total`,`ce`.`race_asian_nonhispanic_females` AS `race_asian_nonhispanic_females`,
		`ce`.`race_asian_nonhispanic_males` AS `race_asian_nonhispanic_males`,`ce`.`race_asian_nonhispanic_unknown` AS `race_asian_nonhispanic_unknown`,`ce`.`race_asian_hispanic_females` AS `race_asian_hispanic_females`,
		`ce`.`race_asian_hispanic_males` AS `race_asian_hispanic_males`,`ce`.`race_asian_hispanic_unknown` AS `race_asian_hispanic_unknown`,`ce`.`race_asian_unknown_females` AS `race_asian_unknown_females`,
		`ce`.`race_asian_unknown_males` AS `race_asian_unknown_males`,`ce`.`race_asian_unknown_unknown` AS `race_asian_unknown_unknown`,`ce`.`race_asian_total` AS `race_asian_total`,`ce`.`race_pi_nonhispanic_females` AS `race_pi_nonhispanic_females`,
		`ce`.`race_pi_nonhispanic_males` AS `race_pi_nonhispanic_males`,`ce`.`race_pi_nonhispanic_unknown` AS `race_pi_nonhispanic_unknown`,`ce`.`race_pi_hispanic_females` AS `race_pi_hispanic_females`,
		`ce`.`race_pi_hispanic_males` AS `race_pi_hispanic_males`,`ce`.`race_pi_hispanic_unknown` AS `race_pi_hispanic_unknown`,`ce`.`race_pi_unknown_females` AS `race_pi_unknown_females`,
		`ce`.`race_pi_unknown_males` AS `race_pi_unknown_males`,`ce`.`race_pi_unknown_unknown` AS `race_pi_unknown_unknown`,`ce`.`race_pi_total` AS `race_pi_total`,`ce`.`race_black_nonhispanic_females` AS `race_black_nonhispanic_females`,
		`ce`.`race_black_nonhispanic_males` AS `race_black_nonhispanic_males`,`ce`.`race_black_nonhispanic_unknown` AS `race_black_nonhispanic_unknown`,`ce`.`race_black_hispanic_females` AS `race_black_hispanic_females`,
		`ce`.`race_black_hispanic_males` AS `race_black_hispanic_males`,`ce`.`race_black_hispanic_unknown` AS `race_black_hispanic_unknown`,`ce`.`race_black_unknown_females` AS `race_black_unknown_females`,
		`ce`.`race_black_unknown_males` AS `race_black_unknown_males`,`ce`.`race_black_unknown_unknown` AS `race_black_unknown_unknown`,`ce`.`race_black_total` AS `race_black_total`,`ce`.`race_white_hispanic_females` AS `race_white_hispanic_females`,
		`ce`.`race_white_hispanic_males` AS `race_white_hispanic_males`,`ce`.`race_white_hispanic_unknown` AS `race_white_hispanic_unknown`,`ce`.`race_white_nonhispanic_females` AS `race_white_nonhispanic_females`,
		`ce`.`race_white_nonhispanic_males` AS `race_white_nonhispanic_males`,`ce`.`race_white_nonhispanic_unknown` AS `race_white_nonhispanic_unknown`,`ce`.`race_white_unknown_females` AS `race_white_unknown_females`,
		`ce`.`race_white_unknown_males` AS `race_white_unknown_males`,`ce`.`race_white_unknown_unknown` AS `race_white_unknown_unknown`,`ce`.`race_white_total` AS `race_white_total`,
		`ce`.`race_multiple_nonhispanic_females` AS `race_multiple_nonhispanic_females`,`ce`.`race_multiple_nonhispanic_males` AS `race_multiple_nonhispanic_males`,`ce`.`race_multiple_nonhispanic_unknown` AS `race_multiple_nonhispanic_unknown`,
		`ce`.`race_multiple_hispanic_females` AS `race_multiple_hispanic_females`,`ce`.`race_multiple_hispanic_males` AS `race_multiple_hispanic_males`,`ce`.`race_multiple_hispanic_unknown` AS `race_multiple_hispanic_unknown`,
		`ce`.`race_multiple_unknown_females` AS `race_multiple_unknown_females`,`ce`.`race_multiple_unknown_males` AS `race_multiple_unknown_males`,`ce`.`race_multiple_unknown_unknown` AS `race_multiple_unknown_unknown`,
		`ce`.`race_multiple_total` AS `race_multiple_total`,`ce`.`race_unknown_nonhispanic_females` AS `race_unknown_nonhispanic_females`,`ce`.`race_unknown_nonhispanic_males` AS `race_unknown_nonhispanic_males`,
		`ce`.`race_unknown_nonhispanic_unknown` AS `race_unknown_nonhispanic_unknown`,`ce`.`race_unknown_hispanic_females` AS `race_unknown_hispanic_females`,`ce`.`race_unknown_hispanic_males` AS `race_unknown_hispanic_males`,
		`ce`.`race_unknown_hispanic_unknown` AS `race_unknown_hispanic_unknown`,`ce`.`race_unknown_unknown_females` AS `race_unknown_unknown_females`,`ce`.`race_unknown_unknown_males` AS `race_unknown_unknown_males`,
		`ce`.`race_unknown_unknown_unknown` AS `race_unknown_unknown_unknown`,`ce`.`race_unknown_total` AS `race_unknown_total`,`ce`.`race_total_nonhispanic_females` AS `race_total_nonhispanic_females`,
		`ce`.`race_total_nonhispanic_males` AS `race_total_nonhispanic_males`,`ce`.`race_total_nonhispanic_unknown` AS `race_total_nonhispanic_unknown`,`ce`.`race_total_hispanic_females` AS `race_total_hispanic_females`,
		`ce`.`race_total_hispanic_males` AS `race_total_hispanic_males`,`ce`.`race_total_hispanic_unknown` AS `race_total_hispanic_unknown`,`ce`.`race_total_unknown_females` AS `race_total_unknown_females`,
		`ce`.`race_total_unknown_males` AS `race_total_unknown_males`,`ce`.`race_total_unknown_unknown` AS `race_total_unknown_unknown`,`ce`.`race_total_total` AS `race_total_total`,`cmc`.`mdc_income_baseline` AS `mdc_income_baseline`,
		`cmc`.`mdc_income_followup` AS `mdc_income_followup`,`cmc`.`mdc_education_baseline` AS `mdc_education_baseline`,`cmc`.`mdc_education_followup` AS `mdc_education_followup`,`cmc`.`mdc_marital_status_baseline` AS `mdc_marital_status_baseline`,
		`cmc`.`mdc_marital_status_followup` AS `mdc_marital_status_followup`,`cmc`.`mdc_language_origin_baseline` AS `mdc_language_origin_baseline`,`cmc`.`mdc_language_origin_followup` AS `mdc_language_origin_followup`,
		`cmc`.`mdc_employment_baseline` AS `mdc_employment_baseline`,`cmc`.`mdc_employment_followup` AS `mdc_employment_followup`,`cmc`.`mdc_health_insurance_baseline` AS `mdc_health_insurance_baseline`,
		`cmc`.`mdc_health_insurance_followup` AS `mdc_health_insurance_followup`,`cmc`.`mdc_anthropometry_baseline` AS `mdc_anthropometry_baseline`,`cmc`.`mdc_anthropometry_followup` AS `mdc_anthropometry_followup`,
		`cmc`.`mdc_dietary_intake_baseline` AS `mdc_dietary_intake_baseline`,`cmc`.`mdc_dietary_intake_followup` AS `mdc_dietary_intake_followup`,`cmc`.`mdc_dietary_supplement_baseline` AS `mdc_dietary_supplement_baseline`,
		`cmc`.`mdc_dietary_supplement_followup` AS `mdc_dietary_supplement_followup`,`cmc`.`mdc_alternative_medicine_baseline` AS `mdc_alternative_medicine_baseline`,`cmc`.`mdc_alternative_medicine_followup` AS `mdc_alternative_medicine_followup`,
		`cmc`.`mdc_prescription_drug_use_baseline` AS `mdc_prescription_drug_use_baseline`,`cmc`.`mdc_prescription_drug_use_followup` AS `mdc_prescription_drug_use_followup`,
		`cmc`.`mdc_nonprescription_drug_use_baseline` AS `mdc_nonprescription_drug_use_baseline`,`cmc`.`mdc_nonprescription_drug_use_followup` AS `mdc_nonprescription_drug_use_followup`,`cmc`.`mdc_alcohol_baseline` AS `mdc_alcohol_baseline`,
		`cmc`.`mdc_alcohol_followup` AS `mdc_alcohol_followup`,`cmc`.`mdc_cigarette_baseline` AS `mdc_cigarette_baseline`,`cmc`.`mdc_cigarette_followup` AS `mdc_cigarette_followup`,
		`cmc`.`mdc_other_tobacco_cigars_baseline` AS `mdc_other_tobacco_cigars_baseline`,`cmc`.`mdc_other_tobacco_cigars_followup` AS `mdc_other_tobacco_cigars_followup`,`cmc`.`mdc_other_tobacco_pipes_baseline` AS `mdc_other_tobacco_pipes_baseline`,
		`cmc`.`mdc_other_tobacco_pipes_followup` AS `mdc_other_tobacco_pipes_followup`,`cmc`.`mdc_other_tobacco_chewing_baseline` AS `mdc_other_tobacco_chewing_baseline`,`cmc`.`mdc_other_tobacco_chewing_followup` AS `mdc_other_tobacco_chewing_followup`,
		`cmc`.`mdc_other_tobacco_ecigarette_baseline` AS `mdc_other_tobacco_ecigarette_baseline`,`cmc`.`mdc_other_tobacco_ecigarette_followup` AS `mdc_other_tobacco_ecigarette_followup`,
		`cmc`.`mdc_other_tobacco_other_baseline` AS `mdc_other_tobacco_other_baseline`,`cmc`.`mdc_other_tobacco_other_followup` AS `mdc_other_tobacco_other_followup`,`cmc`.`mdc_physical_activity_baseline` AS `mdc_physical_activity_baseline`,
		`cmc`.`mdc_physical_activity_followup` AS `mdc_physical_activity_followup`,`cmc`.`mdc_sleep_habits_baseline` AS `mdc_sleep_habits_baseline`,`cmc`.`mdc_sleep_habits_followup` AS `mdc_sleep_habits_followup`,
		`cmc`.`mdc_reproductive_history_baseline` AS `mdc_reproductive_history_baseline`,`cmc`.`mdc_reproductive_history_followup` AS `mdc_reproductive_history_followup`,`cmc`.`mdc_self_reported_health_baseline` AS `mdc_self_reported_health_baseline`,
		`cmc`.`mdc_self_reported_health_followup` AS `mdc_self_reported_health_followup`,`cmc`.`mdc_quality_of_life_baseline` AS `mdc_quality_of_life_baseline`,`cmc`.`mdc_quality_of_life_followup` AS `mdc_quality_of_life_followup`,
		`cmc`.`mdc_social_support_baseline` AS `mdc_social_support_baseline`,`cmc`.`mdc_social_support_followup` AS `mdc_social_support_followup`,
		`cmc`.`mdc_cognitive_function_baseline` AS `mdc_cognitive_function_baseline`,`cmc`.`mdc_cognitive_function_followup` AS `mdc_cognitive_function_followup`,
		`cmc`.`mdc_depression_baseline` AS `mdc_depression_baseline`,`cmc`.`mdc_depression_followup` AS `mdc_depression_followup`,`cmc`.`mdc_other_psychosocial_baseline` AS `mdc_other_psychosocial_baseline`,
		`cmc`.`mdc_other_psychosocial_followup` AS `mdc_other_psychosocial_followup`,`cmc`.`mdc_fatigue_baseline` AS `mdc_fatigue_baseline`,`cmc`.`mdc_fatigue_followup` AS `mdc_fatigue_followup`,
		`cmc`.`mdc_family_hsitory_of_cancer_baseline` AS `mdc_family_hsitory_of_cancer_baseline`,`cmc`.`mdc_family_hsitory_of_cancer_followup` AS `mdc_family_hsitory_of_cancer_followup`,
		`cmc`.`mdc_family_hsitory_of_cancer_pedigrees_baseline` AS `mdc_family_hsitory_of_cancer_pedigrees_baseline`,`cmc`.`mdc_family_hsitory_of_cancer_pedigrees_followup` AS `mdc_family_hsitory_of_cancer_pedigrees_followup`,
		`cmc`.`mdc_environment_baseline` AS `mdc_environment_baseline`,`cmc`.`mdc_environment_followup` AS `mdc_environment_followup`,`cmc`.`mdc_residential_infomation_baseline` AS `mdc_residential_infomation_baseline`,
		`cmc`.`mdc_residential_infomation_followup` AS `mdc_residential_infomation_followup`,
		`cs`.`bio_no_cancer_serum` AS `bio_no_cancer_serum`,`cs`.`bio_no_cancer_buffy` AS `bio_no_cancer_buffy`,`cs`.`bio_no_cancer_saliva` AS `bio_no_cancer_saliva`,
		`cs`.`bio_no_cancer_urine` AS `bio_no_cancer_urine`,`cs`.`bio_no_cancer_feces` AS `bio_no_cancer_feces`,`cs`.`bio_no_cancer_tumor_tissue_1` AS `bio_no_cancer_tumor_tissue_1`,`cs`.`bio_no_cancer_tumor_tissue_2` AS `bio_no_cancer_tumor_tissue_2`,
		`cs`.`bio_oropharyngeal_serum` AS `bio_oropharyngeal_serum`,`cs`.`bio_oropharyngeal_buffy` AS `bio_oropharyngeal_buffy`,`cs`.`bio_oropharyngeal_saliva` AS `bio_oropharyngeal_saliva`,`cs`.`bio_oropharyngeal_urine` AS `bio_oropharyngeal_urine`,
		`cs`.`bio_oropharyngeal_feces` AS `bio_oropharyngeal_feces`,`cs`.`bio_oropharyngeal_tumor_tissue_1` AS `bio_oropharyngeal_tumor_tissue_1`,`cs`.`bio_oropharyngeal_tumor_tissue_2` AS `bio_oropharyngeal_tumor_tissue_2`,`cs`.`bio_esophagus_serum` AS `bio_esophagus_serum`,
		`cs`.`bio_esophagus_buffy` AS `bio_esophagus_buffy`,`cs`.`bio_esophagus_saliva` AS `bio_esophagus_saliva`,`cs`.`bio_esophagus_urine` AS `bio_esophagus_urine`,`cs`.`bio_esophagus_feces` AS `bio_esophagus_feces`,`cs`.`bio_esophagus_tumor_tissue_1` AS `bio_esophagus_tumor_tissue_1`,
		`cs`.`bio_esophagus_tumor_tissue_2` AS `bio_esophagus_tumor_tissue_2`,`cs`.`bio_stomach_serum` AS `bio_stomach_serum`,`cs`.`bio_stomach_buffy` AS `bio_stomach_buffy`,`cs`.`bio_stomach_saliva` AS `bio_stomach_saliva`,`cs`.`bio_stomach_urine` AS `bio_stomach_urine`,
		`cs`.`bio_stomach_feces` AS `bio_stomach_feces`,`cs`.`bio_stomach_tumor_tissue_1` AS `bio_stomach_tumor_tissue_1`,`cs`.`bio_stomach_tumor_tissue_2` AS `bio_stomach_tumor_tissue_2`,`cs`.`bio_small_intestine_serum` AS `bio_small_intestine_serum`,
		`cs`.`bio_small_intestine_buffy` AS `bio_small_intestine_buffy`,`cs`.`bio_small_intestine_saliva` AS `bio_small_intestine_saliva`,
		`cs`.`bio_small_intestine_urine` AS `bio_small_intestine_urine`,`cs`.`bio_small_intestine_feces` AS `bio_small_intestine_feces`,
		`cs`.`bio_small_intestine_tumor_tissue_1` AS `bio_small_intestine_tumor_tissue_1`,`cs`.`bio_small_intestine_tumor_tissue_2` AS `bio_small_intestine_tumor_tissue_2`,`cs`.`bio_colon_serum` AS `bio_colon_serum`,
		`cs`.`bio_colon_buffy` AS `bio_colon_buffy`,`cs`.`bio_colon_saliva` AS `bio_colon_saliva`,
		`cs`.`bio_colon_urine` AS `bio_colon_urine`,`cs`.`bio_colon_feces` AS `bio_colon_feces`,`cs`.`bio_colon_tumor_tissue_1` AS `bio_colon_tumor_tissue_1`,
		`cs`.`bio_colon_tumor_tissue_2` AS `bio_colon_tumor_tissue_2`,`cs`.`bio_rectum_serum` AS `bio_rectum_serum`,`cs`.`bio_rectum_buffy` AS `bio_rectum_buffy`,
		`cs`.`bio_rectum_saliva` AS `bio_rectum_saliva`,`cs`.`bio_rectum_urine` AS `bio_rectum_urine`,`cs`.`bio_rectum_feces` AS `bio_rectum_feces`,`cs`.`bio_rectum_tumor_tissue_1` AS `bio_rectum_tumor_tissue_1`,
		`cs`.`bio_rectum_tumor_tissue_2` AS `bio_rectum_tumor_tissue_2`,`cs`.`bio_liver_serum` AS `bio_liver_serum`,
		`cs`.`bio_liver_buffy` AS `bio_liver_buffy`,`cs`.`bio_liver_saliva` AS `bio_liver_saliva`,`cs`.`bio_liver_urine` AS `bio_liver_urine`,`cs`.`bio_liver_feces` AS `bio_liver_feces`,
		`cs`.`bio_liver_tumor_tissue_1` AS `bio_liver_tumor_tissue_1`,`cs`.`bio_liver_tumor_tissue_2` AS `bio_liver_tumor_tissue_2`,
		`cs`.`bio_gall_bladder_serum` AS `bio_gall_bladder_serum`,`cs`.`bio_gall_bladder_buffy` AS `bio_gall_bladder_buffy`,`cs`.`bio_gall_bladder_saliva` AS `bio_gall_bladder_saliva`,
		`cs`.`bio_gall_bladder_urine` AS `bio_gall_bladder_urine`,`cs`.`bio_gall_bladder_feces` AS `bio_gall_bladder_feces`,
		`cs`.`bio_gall_bladder_tumor_tissue_1` AS `bio_gall_bladder_tumor_tissue_1`,`cs`.`bio_gall_bladder_tumor_tissue_2` AS `bio_gall_bladder_tumor_tissue_2`,`cs`.`bio_pancreas_serum` AS `bio_pancreas_serum`,
		`cs`.`bio_pancreas_buffy` AS `bio_pancreas_buffy`,`cs`.`bio_pancreas_saliva` AS `bio_pancreas_saliva`,
		`cs`.`bio_pancreas_urine` AS `bio_pancreas_urine`,`cs`.`bio_pancreas_feces` AS `bio_pancreas_feces`,`cs`.`bio_pancreas_tumor_tissue_1` AS `bio_pancreas_tumor_tissue_1`,
		`cs`.`bio_pancreas_tumor_tissue_2` AS `bio_pancreas_tumor_tissue_2`,`cs`.`bio_lung_serum` AS `bio_lung_serum`,`cs`.`bio_lung_buffy` AS `bio_lung_buffy`,
		`cs`.`bio_lung_saliva` AS `bio_lung_saliva`,`cs`.`bio_lung_urine` AS `bio_lung_urine`,`cs`.`bio_lung_feces` AS `bio_lung_feces`,`cs`.`bio_lung_tumor_tissue_1` AS `bio_lung_tumor_tissue_1`,
		`cs`.`bio_lung_tumor_tissue_2` AS `bio_lung_tumor_tissue_2`,`cs`.`bio_bone_serum` AS `bio_bone_serum`,`cs`.`bio_bone_buffy` AS `bio_bone_buffy`,
		`cs`.`bio_bone_saliva` AS `bio_bone_saliva`,`cs`.`bio_bone_urine` AS `bio_bone_urine`,`cs`.`bio_bone_feces` AS `bio_bone_feces`,`cs`.`bio_bone_tumor_tissue_1` AS `bio_bone_tumor_tissue_1`,
		`cs`.`bio_bone_tumor_tissue_2` AS `bio_bone_tumor_tissue_2`,`cs`.`bio_melanoma_serum` AS `bio_melanoma_serum`,
		`cs`.`bio_melanoma_buffy` AS `bio_melanoma_buffy`,`cs`.`bio_melanoma_saliva` AS `bio_melanoma_saliva`,`cs`.`bio_melanoma_urine` AS `bio_melanoma_urine`,`cs`.`bio_melanoma_feces` AS `bio_melanoma_feces`,`cs`.`bio_melanoma_tumor_tissue_1` AS `bio_melanoma_tumor_tissue_1`,`cs`.`bio_melanoma_tumor_tissue_2` AS `bio_melanoma_tumor_tissue_2`,
		`cs`.`bio_breast_serum` AS `bio_breast_serum`,`cs`.`bio_breast_buffy` AS `bio_breast_buffy`,`cs`.`bio_breast_saliva` AS `bio_breast_saliva`,`cs`.`bio_breast_urine` AS `bio_breast_urine`,`cs`.`bio_breast_feces` AS `bio_breast_feces`,`cs`.`bio_breast_tumor_tissue_1` AS `bio_breast_tumor_tissue_1`,
		`cs`.`bio_breast_tumor_tissue_2` AS `bio_breast_tumor_tissue_2`,`cs`.`bio_cervix_serum` AS `bio_cervix_serum`,`cs`.`bio_cervix_buffy` AS `bio_cervix_buffy`,`cs`.`bio_cervix_saliva` AS `bio_cervix_saliva`,`cs`.`bio_cervix_urine` AS `bio_cervix_urine`,`cs`.`bio_cervix_feces` AS `bio_cervix_feces`,
		`cs`.`bio_cervix_tumor_tissue_1` AS `bio_cervix_tumor_tissue_1`,`cs`.`bio_cervix_tumor_tissue_2` AS `bio_cervix_tumor_tissue_2`,`cs`.`bio_corpus_serum` AS `bio_corpus_serum`,`cs`.`bio_corpus_buffy` AS `bio_corpus_buffy`,`cs`.`bio_corpus_saliva` AS `bio_corpus_saliva`,`cs`.`bio_corpus_urine` AS `bio_corpus_urine`,
		`cs`.`bio_corpus_feces` AS `bio_corpus_feces`,`cs`.`bio_corpus_tumor_tissue_1` AS `bio_corpus_tumor_tissue_1`,`cs`.`bio_corpus_tumor_tissue_2` AS `bio_corpus_tumor_tissue_2`,`cs`.`bio_ovary_serum` AS `bio_ovary_serum`,`cs`.`bio_ovary_buffy` AS `bio_ovary_buffy`,`cs`.`bio_ovary_saliva` AS `bio_ovary_saliva`,
		`cs`.`bio_ovary_urine` AS `bio_ovary_urine`,`cs`.`bio_ovary_feces` AS `bio_ovary_feces`,`cs`.`bio_ovary_tumor_tissue_1` AS `bio_ovary_tumor_tissue_1`,`cs`.`bio_ovary_tumor_tissue_2` AS `bio_ovary_tumor_tissue_2`,`cs`.`bio_prostate_serum` AS `bio_prostate_serum`,`cs`.`bio_prostate_buffy` AS `bio_prostate_buffy`,
		`cs`.`bio_prostate_saliva` AS `bio_prostate_saliva`,`cs`.`bio_prostate_urine` AS `bio_prostate_urine`,`cs`.`bio_prostate_feces` AS `bio_prostate_feces`,`cs`.`bio_prostate_tumor_tissue_1` AS `bio_prostate_tumor_tissue_1`,`cs`.`bio_prostate_tumor_tissue_2` AS `bio_prostate_tumor_tissue_2`,`cs`.`bio_bladder_serum` AS `bio_bladder_serum`,
		`cs`.`bio_bladder_buffy` AS `bio_bladder_buffy`,`cs`.`bio_bladder_saliva` AS `bio_bladder_saliva`,`cs`.`bio_bladder_urine` AS `bio_bladder_urine`,`cs`.`bio_bladder_feces` AS `bio_bladder_feces`,`cs`.`bio_bladder_tumor_tissue_1` AS `bio_bladder_tumor_tissue_1`,`cs`.`bio_bladder_tumor_tissue_2` AS `bio_bladder_tumor_tissue_2`,
		`cs`.`bio_kidney_serum` AS `bio_kidney_serum`,`cs`.`bio_kidney_buffy` AS `bio_kidney_buffy`,`cs`.`bio_kidney_saliva` AS `bio_kidney_saliva`,`cs`.`bio_kidney_urine` AS `bio_kidney_urine`,`cs`.`bio_kidney_feces` AS `bio_kidney_feces`,`cs`.`bio_kidney_tumor_tissue_1` AS `bio_kidney_tumor_tissue_1`,
		`cs`.`bio_kidney_tumor_tissue_2` AS `bio_kidney_tumor_tissue_2`,`cs`.`bio_brain_serum` AS `bio_brain_serum`,`cs`.`bio_brain_buffy` AS `bio_brain_buffy`,`cs`.`bio_brain_saliva` AS `bio_brain_saliva`,`cs`.`bio_brain_urine` AS `bio_brain_urine`,`cs`.`bio_brain_feces` AS `bio_brain_feces`,
		`cs`.`bio_brain_tumor_tissue_1` AS `bio_brain_tumor_tissue_1`,`cs`.`bio_brain_tumor_tissue_2` AS `bio_brain_tumor_tissue_2`,`cs`.`bio_thyroid_serum` AS `bio_thyroid_serum`,`cs`.`bio_thyroid_buffy` AS `bio_thyroid_buffy`,`cs`.`bio_thyroid_saliva` AS `bio_thyroid_saliva`,`cs`.`bio_thyroid_urine` AS `bio_thyroid_urine`,
		`cs`.`bio_thyroid_feces` AS `bio_thyroid_feces`,`cs`.`bio_thyroid_tumor_tissue_1` AS `bio_thyroid_tumor_tissue_1`,`cs`.`bio_thyroid_tumor_tissue_2` AS `bio_thyroid_tumor_tissue_2`,`cs`.`bio_lymphoma_serum` AS `bio_lymphoma_serum`,`cs`.`bio_lymphoma_buffy` AS `bio_lymphoma_buffy`,`cs`.`bio_lymphoma_saliva` AS `bio_lymphoma_saliva`,
		`cs`.`bio_lymphoma_urine` AS `bio_lymphoma_urine`,`cs`.`bio_lymphoma_feces` AS `bio_lymphoma_feces`,`cs`.`bio_lymphoma_tumor_tissue_1` AS `bio_lymphoma_tumor_tissue_1`,`cs`.`bio_lymphoma_tumor_tissue_2` AS `bio_lymphoma_tumor_tissue_2`,`cs`.`bio_myeloma_serum` AS `bio_myeloma_serum`,`cs`.`bio_myeloma_buffy` AS `bio_myeloma_buffy`,
		`cs`.`bio_myeloma_saliva` AS `bio_myeloma_saliva`,`cs`.`bio_myeloma_urine` AS `bio_myeloma_urine`,`cs`.`bio_myeloma_feces` AS `bio_myeloma_feces`,`cs`.`bio_myeloma_tumor_tissue_1` AS `bio_myeloma_tumor_tissue_1`,`cs`.`bio_myeloma_tumor_tissue_2` AS `bio_myeloma_tumor_tissue_2`,`cs`.`bio_leukemia_serum` AS `bio_leukemia_serum`,
		`cs`.`bio_leukemia_buffy` AS `bio_leukemia_buffy`,`cs`.`bio_leukemia_saliva` AS `bio_leukemia_saliva`,`cs`.`bio_leukemia_urine` AS `bio_leukemia_urine`,`cs`.`bio_leukemia_feces` AS `bio_leukemia_feces`,`cs`.`bio_leukemia_tumor_tissue_1` AS `bio_leukemia_tumor_tissue_1`,`cs`.`bio_leukemia_tumor_tissue_2` AS `bio_leukemia_tumor_tissue_2`,
		`cs`.`bio_all_other_cancers_serum` AS `bio_all_other_cancers_serum`,`cs`.`bio_all_other_cancers_buffy` AS `bio_all_other_cancers_buffy`,`cs`.`bio_all_other_cancers_saliva` AS `bio_all_other_cancers_saliva`,`cs`.`bio_all_other_cancers_urine` AS `bio_all_other_cancers_urine`,`cs`.`bio_all_other_cancers_feces` AS `bio_all_other_cancers_feces`,
		`cs`.`bio_all_other_cancers_tumor_tissue_1` AS `bio_all_other_cancers_tumor_tissue_1`,`cs`.`bio_all_other_cancers_tumor_tissue_2` AS `bio_all_other_cancers_tumor_tissue_2`,`cs`.`bio_blood_baseline` AS `bio_blood_baseline`,`cs`.`bio_blood_baseline_serum` AS `bio_blood_baseline_serum`,`cs`.`bio_blood_baseline_plasma` AS `bio_blood_baseline_plasma`,
		`cs`.`bio_blood_baseline_buffy_coat` AS `bio_blood_baseline_buffy_coat`,`cs`.`bio_blood_baseline_other_derivative` AS `bio_blood_baseline_other_derivative`,`cs`.`bio_blood_other_time` AS `bio_blood_other_time`,`cs`.`bio_blood_other_time_serum` AS `bio_blood_other_time_serum`,`cs`.`bio_blood_other_time_plasma` AS `bio_blood_other_time_plasma`,
		`cs`.`bio_blood_other_time_buffy_coat` AS `bio_blood_other_time_buffy_coat`,`cs`.`bio_blood_other_time_other_derivative` AS `bio_blood_other_time_other_derivative`,`cs`.`bio_buccal_saliva_baseline` AS `bio_buccal_saliva_baseline`,`cs`.`bio_buccal_saliva_other_time` AS `bio_buccal_saliva_other_time`,`cs`.`bio_tissue_baseline` AS `bio_tissue_baseline`,
		`cs`.`bio_tissue_other_time` AS `bio_tissue_other_time`,`cs`.`bio_tumor_block_info` AS `bio_tumor_block_info`,`cs`.`bio_genotyping_data` AS `bio_genotyping_data`,`cs`.`bio_sequencing_data_exome` AS `bio_sequencing_data_exome`,`cs`.`bio_sequencing_data_whole_genome` AS `bio_sequencing_data_whole_genome`,
		`cs`.`bio_epigenetic_or_metabolic_markers` AS `bio_epigenetic_or_metabolic_markers`,`cs`.`bio_other_omics_data` AS `bio_other_omics_data`,
		`cc`.`ci_oropharyngeal_male` AS `ci_oropharyngeal_male`,`cc`.`ci_oropharyngeal_female` AS `ci_oropharyngeal_female`,`cc`.`ci_esophagus_male` AS `ci_esophagus_male`,
		`cc`.`ci_esophagus_female` AS `ci_esophagus_female`,`cc`.`ci_stomach_male` AS `ci_stomach_male`,`cc`.`ci_stomach_female` AS `ci_stomach_female`,`cc`.`ci_small_intestine_male` AS `ci_small_intestine_male`,`cc`.`ci_small_intestine_female` AS `ci_small_intestine_female`,`cc`.`ci_colon_male` AS `ci_colon_male`,
		`cc`.`ci_colon_female` AS `ci_colon_female`,`cc`.`ci_rectum_male` AS `ci_rectum_male`,`cc`.`ci_rectum_female` AS `ci_rectum_female`,`cc`.`ci_gall_bladder_male` AS `ci_gall_bladder_male`,`cc`.`ci_gall_bladder_female` AS `ci_gall_bladder_female`,`cc`.`ci_pancreas_male` AS `ci_pancreas_male`,
		`cc`.`ci_pancreas_female` AS `ci_pancreas_female`,`cc`.`ci_lung_male` AS `ci_lung_male`,`cc`.`ci_lung_female` AS `ci_lung_female`,`cc`.`ci_bone_male` AS `ci_bone_male`,`cc`.`ci_bone_female` AS `ci_bone_female`,`cc`.`ci_melanoma_male` AS `ci_melanoma_male`,`cc`.`ci_melanoma_female` AS `ci_melanoma_female`,
		`cc`.`ci_breast_male` AS `ci_breast_male`,`cc`.`ci_breast_female` AS `ci_breast_female`,`cc`.`ci_cervix_male` AS `ci_cervix_male`,`cc`.`ci_cervix_female` AS `ci_cervix_female`,`cc`.`ci_corpus_male` AS `ci_corpus_male`,`cc`.`ci_corpus_female` AS `ci_corpus_female`,`cc`.`ci_ovary_male` AS `ci_ovary_male`,
		`cc`.`ci_ovary_female` AS `ci_ovary_female`,`cc`.`ci_prostate_male` AS `ci_prostate_male`,`cc`.`ci_prostate_female` AS `ci_prostate_female`,`cc`.`ci_bladder_male` AS `ci_bladder_male`,`cc`.`ci_bladder_female` AS `ci_bladder_female`,`cc`.`ci_kidney_male` AS `ci_kidney_male`,`cc`.`ci_kidney_female` AS `ci_kidney_female`,
		`cc`.`ci_brain_male` AS `ci_brain_male`,`cc`.`ci_brain_female` AS `ci_brain_female`,`cc`.`ci_thyroid_male` AS `ci_thyroid_male`,`cc`.`ci_thyroid_female` AS `ci_thyroid_female`,`cc`.`ci_lymphoma_male` AS `ci_lymphoma_male`,`cc`.`ci_lymphoma_female` AS `ci_lymphoma_female`,`cc`.`ci_myeloma_male` AS `ci_myeloma_male`,
		`cc`.`ci_myeloma_female` AS `ci_myeloma_female`,`cc`.`ci_leukemia_male` AS `ci_leukemia_male`,`cc`.`ci_leukemia_female` AS `ci_leukemia_female`,`cc`.`ci_liver_male` AS `ci_liver_male`,`cc`.`ci_liver_female` AS `ci_liver_female`,`cc`.`ci_all_other_cancers_male` AS `ci_all_other_cancers_male`,
		`cc`.`ci_all_other_cancers_female` AS `ci_all_other_cancers_female`,`cc`.`ci_cancer_treatment_data` AS `ci_cancer_treatment_data` 
    FROM 
		((((`cohort_basic` `cb` 
		LEFT JOIN `cohort_enrollment` `ce` on((`cb`.`cohort_id` = `ce`.`cohort_id`))) 
		LEFT JOIN`cohort_major_content` `cmc` on((`cb`.`cohort_id` = `cmc`.`cohort_id`))) 
		LEFT JOIN`cohort_specimens` `cs` on((`cb`.`cohort_id` = `cs`.`cohort_id`))) 
		LEFT JOIN`cohort_cancer` `cc` on((`cb`.`cohort_id` = `cc`.`cohort_id`))) ;
    

